version: '3'

services:
  logup_server:
    image: logup
    container_name: "logup_server"
    ports:
      - '8080:8080'
    networks:
      - internal_network
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio_storage
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=logstorage
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - internal_network
    volumes:
      - './minio_data:/data'
    restart: unless-stopped

networks:
  internal_network:
    driver: bridge